#!/usr/bin/with-contenv bash

setting_file=/setting.lock
out_html_dir=/out/html
out_dir=/out
scan_dir=/Scan

function setting {

    touch $setting_file

    # 创建文件和文件夹
	if [ ! -d $out_dir ]; then
		mkdir -p $out_dir
	fi

	if [ ! -d $out_html_dir ]; then
		mkdir -p $out_html_dir
	fi

	if [ ! -d $scan_dir ]; then
		mkdir -p $scan_dir
	fi

    # 设置时区
    ln -sf /usr/share/zoneinfo/$TZ   /etc/localtime
    echo $TZ > /etc/timezone

    # 设置Crontab定时任务
	crontab -r
    (crontab -l ; echo "${CRON} su-exec ${PUID}:${PGID} linuxdir2html /Scan /out/html/index") | crontab -

}

if [ ! -f $setting_file ]; then
	setting
fi

chown ${PUID}:${PGID} $out_dir $scan_dir $log_dir $out_html_dir
umask ${UMASK}
echo -e "\033[32m以PUID=${PUID},PGID=${PGID},umask=${UMASK}的身份启动程序\033[0m"

echo -e "\033[32mCron 定时任务预览\033[0m"
crontab -l

echo -e "\033[34m测试linuxdir2html程序\033[0m"
su-exec ${PUID}:${PGID} linuxdir2html /Scan /out/html/index

